### ISSUE TITLE
Keep getting an error with the OsuLastFM Scrobbler

### ISSUE THREAD

**Issue by Carlosk12xd** [iMyon/OsuLastfmScrobbler#3]
Hello I keep getting an error from the OsuRT Plugin. It says illegal characters in path, was there an update that messed the plugin up?
Before this it worked perfectly!!

```
[7:00:33 PM] [OsuRTDataProviderPlugin][ID:0]Init HitEventFinder Failed! Retry after 3 seconds

[7:00:33 PM] [OsuRTDataProviderPlugin]------------- ORTDP(Exception)--------------- 
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at OsuRTDataProvider.Memory.OsuBeatmapFinder.GetCurrentBeatmap(Int32 osu_id)

[7:00:33 PM] [OsuRTDataProviderPlugin]------------- ORTDP(Exception)--------------- 
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at OsuRTDataProvider.Memory.OsuBeatmapFinder.GetCurrentBeatmap(Int32 osu_id)

[7:00:33 PM] [OsuRTDataProviderPlugin]------------- ORTDP(Exception)--------------- 
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at OsuRTDataProvider.Memory.OsuBeatmapFinder.GetCurrentBeatmap(Int32 osu_id)

[7:00:33 PM] [OsuRTDataProviderPlugin]------------- ORTDP(Exception)--------------- 
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at OsuRTDataProvider.Memory.OsuBeatmapFinder.GetCurrentBeatmap(Int32 osu_id)

[7:00:33 PM] [OsuRTDataProviderPlugin]------------- ORTDP(Exception)--------------- 
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at OsuRTDataProvider.Memory.OsuBeatmapFinder.GetCurrentBeatmap(Int32 osu_id)

[7:00:33 PM] [OsuRTDataProviderPlugin]------------- ORTDP(Exception)--------------- 
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at OsuRTDataProvider.Memory.OsuBeatmapFinder.GetCurrentBeatmap(Int32 osu_id)

[7:00:33 PM] [OsuRTDataProviderPlugin]------------- ORTDP(Exception)--------------- 
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at OsuRTDataProvider.Memory.OsuBeatmapFinder.GetCurrentBeatmap(Int32 osu_id)

[7:00:34 PM] [OsuRTDataProviderPlugin]------------- ORTDP(Exception)--------------- 
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at OsuRTDataProvider.Memory.OsuBeatmapFinder.GetCurrentBeatmap(Int32 osu_id)

[7:00:34 PM] [OsuRTDataProviderPlugin]------------- ORTDP(Exception)--------------- 
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at OsuRTDataProvider.Memory.OsuBeatmapFinder.GetCurrentBeatmap(Int32 osu_id)

[7:00:34 PM] [OsuRTDataProviderPlugin]------------- ORTDP(Exception)--------------- 
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at OsuRTDataProvider.Memory.OsuBeatmapFinder.GetCurrentBeatmap(Int32 osu_id)

[7:00:34 PM] [OsuRTDataProviderPlugin]------------- ORTDP(Exception)--------------- 
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at OsuRTDataProvider.Memory.OsuBeatmapFinder.GetCurrentBeatmap(Int32 osu_id)

[7:00:34 PM] [OsuRTDataProviderPlugin]------------- ORTDP(Exception)--------------- 
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at OsuRTDataProvider.Memory.OsuBeatmapFinder.GetCurrentBeatmap(Int32 osu_id)

[7:00:34 PM] [OsuRTDataProviderPlugin]------------- ORTDP(Exception)--------------- 
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at OsuRTDataProvider.Memory.OsuBeatmapFinder.GetCurrentBeatmap(Int32 osu_id)

[7:00:34 PM] [OsuRTDataProviderPlugin]System.NullReferenceException: Object reference not set to an instance of an object.
   at OsuLastfmScrobbler.client.OsuScrobbler.<HandleListenerEvents>b__15_1(Int32 ms)
   at OsuRTDataProvider.Listen.OsuListenerManager.ListenLoopUpdate() 


```

**Comment by iMyon** [comment]
Try the [latest version](https://github.com/iMyon/OsuLastfmScrobbler/releases/), mayby it works.
[OsuRTDataProvider](https://github.com/OsuSync/OsuRTDataProvider) has no updates for a long time, I tried to fix it. But If this release still doesn't work on your pc, we'll have to wait for the OsuRTDataProvider to be updated.

**Comment by Carlosk12xd** [comment]
This solved the issue, it is working now!! 
Thank you so much :,)
